// +build stanfordrel

package treebank

import "github.com/sapariduo/lingua"

var dependencyTable map[string]lingua.DependencyType = map[string]lingua.DependencyType{
	"root":       lingua.Root,
	"dep":        lingua.Dep,
	"aux":        lingua.Aux,
	"auxpass":    lingua.AuxPass,
	"cop":        lingua.Cop,
	"arg":        lingua.Arg,
	"agent":      lingua.Agent,
	"comp":       lingua.Comp,
	"acomp":      lingua.AComp,
	"ccomp":      lingua.CComp,
	"xcomp":      lingua.XComp,
	"obj":        lingua.Obj,
	"dobj":       lingua.DObj,
	"iobj":       lingua.IObj,
	"pobj":       lingua.PObj,
	"subj":       lingua.Subj,
	"nsubj":      lingua.NSubj,
	"nsubjpass":  lingua.NSubjPass,
	"csubj":      lingua.CSubj,
	"csubjpass":  lingua.CSubjPass,
	"cc":         lingua.Coordination,
	"conj":       lingua.Conj,
	"expl":       lingua.Expl,
	"mod":        lingua.Mod,
	"amod":       lingua.AMod,
	"appos":      lingua.Appos,
	"advcl":      lingua.Advcl,
	"det":        lingua.Det,
	"predet":     lingua.Predet,
	"preconj":    lingua.Preconj,
	"vmod":       lingua.Vmod,
	"mwe":        lingua.MWE,
	"mark":       lingua.Mark,
	"advmod":     lingua.AdvMod,
	"neg":        lingua.Neg,
	"rcmod":      lingua.RCMod,
	"quantmod":   lingua.QuantMod,
	"nn":         lingua.NounMod,
	"npadvmod":   lingua.NPAdvMod,
	"tmod":       lingua.TMod,
	"num":        lingua.Num,
	"number":     lingua.NumberElement,
	"prep":       lingua.Prep,
	"poss":       lingua.Poss,
	"possessive": lingua.Possessive,
	"prt":        lingua.PRT,
	"parataxis":  lingua.Parataxis,
	"goeswith":   lingua.GoesWith,
	"punct":      lingua.Punct,
	"ref":        lingua.Ref,
	"sdep":       lingua.SDep,
	"xsubj":      lingua.XSubj,

	// additional stuff not found in the original, but found in EWT
	"case":       lingua.Case,
	"compound":   lingua.Compound,
	"nmod":       lingua.NMod,
	"discourse":  lingua.Discourse,
	"nummod":     lingua.NumMod,
	"relcl":      lingua.RelCl,
	"nfincl":     lingua.NFinCl,
	"nmod:poss":  lingua.NMod_Poss,
	"nmod:npmod": lingua.NMod_NPMod,
	"vocative":   lingua.Vocative,
	"list":       lingua.List,
	"mwprep":     lingua.MWPrep,
	"remnant":    lingua.Remnant,
	"acl":        lingua.Acl,
	"npmod":      lingua.NPMod,
	"mdvod":      lingua.MDVod,
	"detmod":     lingua.DetMod,

	// found in NNParser
	"pcomp": lingua.PComp,

	"-NULL-": lingua.Dep,
}
